namespace: demo 
nameOverride: ""
replicas: 3
image:
  repository: "vinaykp26/demoapp"
  tag: "1.0.2"
imagePullSecrets: docker-registry
securityContext:
  privileged: false
  runAsUser: 1001
  runAsGroup: 1001
service:
  type: NodePort
  port: "8001"
  targetPort: "8001"
resources:
  limits:
    memory: 200Mi
    cpu: 50m
  requests:
    memory: 50Mi
    cpu: 10m
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
istio:
  enabled: true
  istioIngressNamespace: istio-system
  gatewayName: demo-gateway
  host: "34.170.40.228.nip.io"
  uri:
    prefix: "/api/v1/"