apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{.Values.namespace}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}