apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
    version: {{.Chart.AppVersion}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Chart.Name}}
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}